/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sqlite;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import sqlite.MetodosBase;
/**
 *
 * @author JorgePc
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        conectBt = new javax.swing.JButton();
        tablaBt = new javax.swing.JButton();
        insertBt = new javax.swing.JButton();
        verBt = new javax.swing.JButton();
        modificarBt = new javax.swing.JButton();
        borrarBt = new javax.swing.JButton();
        nometxt = new javax.swing.JTextField();
        idtxt = new javax.swing.JTextField();
        idadetxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        apelidostxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        conectBt.setText("Conectar");
        conectBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                conectBtMouseClicked(evt);
            }
        });
        jPanel1.add(conectBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 120, 50));

        tablaBt.setText("Nueva Tabla");
        tablaBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaBtMouseClicked(evt);
            }
        });
        jPanel1.add(tablaBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 120, 50));

        insertBt.setText("Insertar");
        insertBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insertBtMouseClicked(evt);
            }
        });
        insertBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBtActionPerformed(evt);
            }
        });
        jPanel1.add(insertBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 120, 50));

        verBt.setText("Ver");
        verBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verBtMouseClicked(evt);
            }
        });
        jPanel1.add(verBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 120, 50));

        modificarBt.setText("Modificar");
        modificarBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarBtMouseClicked(evt);
            }
        });
        jPanel1.add(modificarBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 120, 50));

        borrarBt.setText("Borrar");
        borrarBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrarBtMouseClicked(evt);
            }
        });
        jPanel1.add(borrarBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 120, 50));

        nometxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nometxtActionPerformed(evt);
            }
        });
        jPanel1.add(nometxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 120, 30));

        idtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtxtActionPerformed(evt);
            }
        });
        jPanel1.add(idtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 120, 30));

        idadetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idadetxtActionPerformed(evt);
            }
        });
        jPanel1.add(idadetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 120, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Idade");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 90, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 90, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Apelidos");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 90, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Nome");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 90, 30));

        apelidostxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apelidostxtActionPerformed(evt);
            }
        });
        jPanel1.add(apelidostxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 120, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertBtActionPerformed

    private void idadetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idadetxtActionPerformed

    }//GEN-LAST:event_idadetxtActionPerformed

    MetodosBase mt = new MetodosBase();
    
    
    private void conectBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conectBtMouseClicked
        mt.conectar();
    }//GEN-LAST:event_conectBtMouseClicked

    private void tablaBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaBtMouseClicked
       mt.crearNuevaTabla();
    }//GEN-LAST:event_tablaBtMouseClicked

    private void insertBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertBtMouseClicked
       MetodosBase.nome=this.nometxt.getText();
       MetodosBase.apellidos=this.apelidostxt.getText();
       MetodosBase.edad = Integer.parseInt(this.idadetxt.getText());
        mt.insertar();
    }//GEN-LAST:event_insertBtMouseClicked

    private void verBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verBtMouseClicked
       
        mt.ver();
    }//GEN-LAST:event_verBtMouseClicked

    private void modificarBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarBtMouseClicked
       MetodosBase.nome=this.nometxt.getText();
       MetodosBase.apellidos=this.apelidostxt.getText();
       MetodosBase.edad = Integer.parseInt(this.idadetxt.getText());
       MetodosBase.id= Integer.parseInt(this.idtxt.getText());
        mt.update();
    }//GEN-LAST:event_modificarBtMouseClicked

    private void borrarBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarBtMouseClicked
        MetodosBase.id= Integer.parseInt(this.idtxt.getText());
        mt.delete();
    }//GEN-LAST:event_borrarBtMouseClicked

    private void idtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtxtActionPerformed
      
    }//GEN-LAST:event_idtxtActionPerformed

    private void nometxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nometxtActionPerformed

    }//GEN-LAST:event_nometxtActionPerformed

    private void apelidostxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apelidostxtActionPerformed
       
    }//GEN-LAST:event_apelidostxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apelidostxt;
    private javax.swing.JButton borrarBt;
    private javax.swing.JButton conectBt;
    private javax.swing.JTextField idadetxt;
    private javax.swing.JTextField idtxt;
    private javax.swing.JButton insertBt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modificarBt;
    private javax.swing.JTextField nometxt;
    private javax.swing.JButton tablaBt;
    private javax.swing.JButton verBt;
    // End of variables declaration//GEN-END:variables
}
